eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8084/eureka
    instance:
        prefer-ip-address: true
server:
    port: 8086
spring:
    application:
        name: CONFIG-SERVER
   